// Two renderings of the same findings: one for the terminal, one for a file
// you can commit, diff between runs, or send to a client.

const COLOR = process.env.NO_COLOR === undefined && process.stdout.isTTY;
const c = (code, s) => (COLOR ? `\x1b[${code}m${s}\x1b[0m` : s);
const red = (s) => c('31', s);
const yellow = (s) => c('33', s);
const blue = (s) => c('36', s);
const dim = (s) => c('2', s);
const bold = (s) => c('1', s);

const MARK = { error: '✗', warn: '!', info: '·' };
const PAINT = { error: red, warn: yellow, info: blue };

/** Findings grouped by check, worst level first, biggest group first. */
export function group(findings) {
  const order = { error: 0, warn: 1, info: 2 };
  const byId = new Map();
  for (const finding of findings) {
    const entry = byId.get(finding.id) ?? { ...finding, items: [] };
    entry.items.push(finding);
    entry.level = order[finding.level] < order[entry.level] ? finding.level : entry.level;
    byId.set(finding.id, entry);
  }
  return [...byId.values()].sort(
    (a, b) => order[a.level] - order[b.level] || b.items.length - a.items.length,
  );
}

export function counts(findings) {
  return {
    error: findings.filter((x) => x.level === 'error').length,
    warn: findings.filter((x) => x.level === 'warn').length,
    info: findings.filter((x) => x.level === 'info').length,
  };
}

export function terminal(findings, meta) {
  const lines = [];
  const n = counts(findings);

  lines.push('');
  lines.push(bold(`  ${meta.origin}`));
  lines.push(
    dim(
      `  ${meta.pages} pages · ${meta.requests} requests · ${(meta.ms / 1000).toFixed(1)}s` +
        (meta.ignored ? ` · ${meta.ignored} ignored` : ''),
    ),
  );
  lines.push('');

  if (!findings.length) {
    lines.push(`  ${c('32', '✓')} nothing to report`);
    lines.push('');
    return lines.join('\n');
  }

  for (const entry of group(findings)) {
    const paint = PAINT[entry.level];
    const count = entry.items.length;
    lines.push(
      `  ${paint(MARK[entry.level])} ${bold(entry.title)}${count > 1 ? dim(` ×${count}`) : ''}`,
    );
    // One example in full, then the other pages by URL only — the detail
    // repeats and the list is what you act on.
    lines.push(`    ${dim(entry.items[0].detail)}`);
    for (const item of entry.items.slice(0, 8)) {
      lines.push(`    ${dim('·')} ${item.url ?? ''}`);
    }
    if (count > 8) lines.push(`    ${dim(`… and ${count - 8} more`)}`);
    lines.push('');
  }

  lines.push(
    `  ${red(`${n.error} error`)}  ${yellow(`${n.warn} warning`)}  ${blue(`${n.info} note`)}`,
  );
  lines.push('');
  return lines.join('\n');
}

export function markdown(findings, meta) {
  const n = counts(findings);
  const out = [];

  out.push(`# SEO audit — ${meta.origin}`);
  out.push('');
  out.push(
    `${meta.date} · ${meta.pages} pages crawled · **${n.error} errors, ${n.warn} warnings, ${n.info} notes**`,
  );
  out.push('');

  if (!findings.length) {
    out.push('Nothing to report.');
    out.push('');
    return out.join('\n');
  }

  out.push('## Summary');
  out.push('');
  out.push('| | Finding | Pages |');
  out.push('|---|---|---:|');
  for (const entry of group(findings)) {
    out.push(`| ${MARK[entry.level]} | ${entry.title} | ${entry.items.length} |`);
  }
  out.push('');

  for (const level of ['error', 'warn', 'info']) {
    const entries = group(findings).filter((e) => e.level === level);
    if (!entries.length) continue;
    out.push(`## ${{ error: 'Errors', warn: 'Warnings', info: 'Notes' }[level]}`);
    out.push('');
    for (const entry of entries) {
      out.push(`### ${entry.title}`);
      out.push('');
      // Every item carries its own detail (word counts, filenames, hop
      // chains), so each line stands alone rather than repeating a shared
      // preamble that only fits the first one.
      for (const item of entry.items) {
        out.push(`- ${item.url ?? ''}${item.detail ? `  \n  ${item.detail}` : ''}`);
      }
      out.push('');
    }
  }

  out.push('---');
  out.push('');
  out.push(
    'Performance and Core Web Vitals are deliberately not measured here — use ' +
      '[PageSpeed Insights](https://pagespeed.web.dev) and [WebPageTest](https://webpagetest.org), ' +
      'which run real browsers. Generated by [seo-audit](https://github.com/nurkamol/seo-audit).',
  );
  out.push('');
  return out.join('\n');
}

/** Baseline comparison: what changed since the last run, and nothing else. */
export function diffReport({ added, fixed, unchanged, previousDate }) {
  const lines = [''];

  if (fixed.length) {
    lines.push(`  ${c('32', `✓ ${fixed.length} fixed since ${previousDate}`)}`);
    for (const item of fixed.slice(0, 10)) {
      lines.push(`    ${dim('·')} ${item.title} ${dim(item.url ?? '')}`);
    }
    if (fixed.length > 10) lines.push(`    ${dim(`… and ${fixed.length - 10} more`)}`);
    lines.push('');
  }

  if (added.length) {
    lines.push(`  ${red(`✗ ${added.length} new since ${previousDate}`)}`);
    for (const entry of group(added)) {
      lines.push(`    ${PAINT[entry.level](MARK[entry.level])} ${bold(entry.title)}`);
      lines.push(`      ${dim(entry.items[0].detail)}`);
      for (const item of entry.items.slice(0, 6)) lines.push(`      ${dim('·')} ${item.url ?? ''}`);
    }
    lines.push('');
  }

  if (!added.length && !fixed.length) {
    lines.push(`  ${c('32', '✓')} no change since ${previousDate} ${dim(`(${unchanged} known)`)}`);
    lines.push('');
  } else {
    lines.push(dim(`  ${unchanged} unchanged`));
    lines.push('');
  }

  return lines.join('\n');
}
